version: '3.8'

services:
  backend:
    build: ./backend
    platform: linux/amd64
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/habitdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
    volumes:
      - ./backend:/app
    command: ["./wait-for-db.sh", "db", "5432", "python", "run.py"]

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=habitdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
