"""Initial schema with habits and check-ins

Revision ID: 86886dfe4750
Revises: 
Create Date: 2025-05-13 23:27:28.074214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86886dfe4750'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('check_ins', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('habits', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('habits', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('habits', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'updated_at')
    op.drop_column('habits', 'created_at')
    op.drop_column('habits', 'description')
    op.drop_column('check_ins', 'created_at')
    # ### end Alembic commands ###
